classes:
    - admin
    - admin::curl
    - apache
    - mysql
    - mysql::server
    - mysql::client
    - mysql::phpdriver
    - n98magerun
    - modman
    - xdebug
apache_vhosts:
    mybox.dev:
        domain: 'mybox.dev'
    vhost2:
        domain: 'second.box'
apache_modules:
    mod_rewrite:
        name: rewrite
apache_chown:
    - user: 'sebastian'
      group: 'vagrant'
      uid: 505
      gid: 1000
admin_ppas:
    ondrej/php5-oldstable:
        apt_key: E5267A6C
        launchpad_id: 'ondrej'
        priority: 1001
admin_ppa_php: ondrej/php5-oldstable
mysql_password: secret123
mysql_dbs:
    magento:
        user: root
        password: secret123
n98magerun:
    magento_version: magento-ce-1.7.0.2
    installation_folder: /var/www/mybox.dev
    db_host: 127.0.0.1
    db_user: root
    db_pass: secret123
    db_name: magento
    base_url: mybox.dev
    install_sample_data: true
xdebug:
    config:
        xdebug_remote_enable: 1
        xdebug_remote_host: 10.0.2.2
        xdebug_remote_port: 9000
        xdebug_remote_autostart: 0
        xdebug_idekey: 'XDEBUG_macgdbp'