classes:
    - admin
    - admin::curl
    - mysql
    - mysql::server
    - mysql::client
    - mysql::phpdriver
    - n98magerun
    - modman
    - xdebug


####
#
# APACHE vHost 
#
####
apache_vhosts:
    vhost_1:
        domain: 'myproject.dev'
        docroot: '/var/www/myproject'
    vhost_2:
        domain: 'second.box'
        docroot: '/var/www/default'


####
#
# APACHE modules 
#
####
apache_modules:
    mod_rewrite:
        name: rewrite


####
#
# PHP versions 
#
####
admin_ppas:
    # same as admin_ppa_php:
    #--------- php 5.4
    #ondrej/php5-oldstable:
    #--------- php 5.5
    ondrej/php5: 
    #--------- php 5.6
    # ondrej/php5-5.6:
        apt_key: E5267A6C
        launchpad_id: 'ondrej'
        priority: 1001
    ondrej/apache2:
        apt_key: E5267A6C
        launchpad_id: 'ondrej'
        priority: 1001

#--------- php 5.4
# admin_ppa_php: ondrej/php5-oldstable
#--------- php 5.5
admin_ppa_php: ondrej/php5
#--------- php 5.6
# admin_ppa_php: ondrej/php5-5.6


####
#
# MySql  
#
####
mysql_password: secret123
mysql_dbs:
    magento:
        user: root
        password: secret123

####
#
# N98-magerun 
#
####
n98magerun:
    magento_version: magento-mirror-1.9.1.1
    installation_folder: /var/www/myproject
    db_host: 127.0.0.1
    db_user: root
    db_pass: secret123
    db_name: magento
    base_url: myproject.dev
    install_sample_data: false
xdebug:
    config:
        xdebug_remote_enable: 1
        xdebug_remote_host: 10.0.2.2
        xdebug_remote_port: 9000
        xdebug_remote_autostart: 0
        xdebug_idekey: 'XDEBUG_macgdbp'