classes:
    - admin
    - admin::curl
    - mysql
    - mysql::server
    - mysql::client
    - mysql::phpdriver
    - n98magerun
    - modman
    - xdebug
apache_vhosts:
    mybox.dev:
        domain: 'mybox.dev'
    default:
        domain: 'second.box'
apache_modules:
    mod_rewrite:
        name: rewrite
admin_ppas:
    # same as admin_ppa_php:
    #--------- php 5.4
    #ondrej/php5-oldstable:
    #--------- php 5.5
    ondrej/php5: 
    #--------- php 5.6
    # ondrej/php5-5.6:
        apt_key: E5267A6C
        launchpad_id: 'ondrej'
        priority: 1001
    ondrej/apache2:
        apt_key: E5267A6C
        launchpad_id: 'ondrej'
        priority: 1001

#--------- php 5.4
# admin_ppa_php: ondrej/php5-oldstable
#--------- php 5.5
admin_ppa_php: ondrej/php5
#--------- php 5.6
# admin_ppa_php: ondrej/php5-5.6
mysql_password: secret123
mysql_dbs:
    magento:
        user: root
        password: secret123
n98magerun:
    magento_version: magento-ce-1.8.1.0
    installation_folder: /var/www/mybox.dev
    db_host: 127.0.0.1
    db_user: root
    db_pass: secret123
    db_name: magento
    base_url: mybox.dev
    install_sample_data: false
xdebug:
    config:
        xdebug_remote_enable: 1
        xdebug_remote_host: 10.0.2.2
        xdebug_remote_port: 9000
        xdebug_remote_autostart: 0
        xdebug_idekey: 'XDEBUG_macgdbp'