---
vm:
    box: ubuntu/trusty64
    box_url: 'https://atlas.hashicorp.com/ubuntu/boxes/trusty64'
    hostname: vagrant.mybox.dev
    network:
        private_network: 192.168.2.160
    synced_folder:
        folder_1:
            disabled: false
            host: www/default
            guest: /var/www/default
            create: true
        folder_2:
            disabled: false
            host: www/myproject
            guest: /var/www/myproject
            create: true
        folder_3:
            disabled: false
            host: www/logs
            guest: /var/www/logs
            create: true
    provider:
        virtualbox:
            modifyvm:
                natdnshostresolver1: 'on'
                memory: '4096'
    provision:
        puppet:
            manifests_path: puppet/manifests/
            manifest_file: site.pp
            module_path: puppet/modules
            options:
                - '--verbose'
                - '--debug'
