---
vm:
    box: precise64
    box_url: 'http://files.vagrantup.com/precise64.box'
    hostname: vagrant.mybox.dev
    network:
        private_network: 192.168.2.2
    nfs_map_uid: 505
    nfs_map_gid: 1000
    synced_folder:
        folder_1:
            disabled: false
            host: www/default
            guest: /var/www/default
            create: true
        folder_2:
            disabled: false
            host: www/mybox.dev
            guest: /var/www/mybox.dev
            create: true
    provider:
        virtualbox:
            modifyvm:
                natdnshostresolver1: 'on'
                memory: '4096'
    provision:
        puppet:
            manifests_path: puppet/manifests/
            manifest_file: site.pp
            module_path: puppet/modules
            options:
                - '--verbose'
                - '--debug'
